[MAT-185] 사용자가 참여한 경기 리스트를 조회 api 구현
prgrms-web-devcourse/Team_CherryBoys_MatchUs_BE pull request #57
Opened 2021-12-14 19:06 UTC by sunH0

## 작업 사항

- 사용자가 참여한 경기 리스트를 조회 -> 리뷰 완료된 매칭만 조회
- 날짜 순으로 정렬 후 리턴

2021-12-14 20:10 UTC, samkimuel requested changes
고생하셨습니다! 간단한 코멘트 하나만 확인해주세요!

2021-12-14 20:10 UTC, samkimuel commented on src/main/java/com/matchus/domains/user/domain/User.java
> +								.getPeriod()
```suggestion
							 userMatchHistory -> userMatchHistory
								.getMatch()
								.getPeriod()
```

2021-12-14 20:10 UTC, samkimuel commented on src/main/java/com/matchus/domains/user/domain/User.java
> +								.getPeriod()
타입 명시를 안해주면 동작이 안되나용??

2021-12-14 20:44 UTC, sunH0 commented on src/main/java/com/matchus/domains/user/domain/User.java
> +								.getPeriod()
넵!  Comparator.comparing 이  Function<T,R>을 인자로 받고 있어서 객체 타입을 명시해 줘야 한다고 알고 있습니다.
return (V v) -> apply(before.apply(v));

2021-12-15 05:55 UTC, samkimuel approved these changes
고생하셨씁니다!! 끝까지 ㄱㅈㅇ~

2021-12-15 05:55 UTC, merged