[MAT-191] 팀 초대 리스트 조회
prgrms-web-devcourse/Team_CherryBoys_MatchUs_BE pull request #69
Opened 2021-12-15 18:56 UTC by sunH0

## 작업 사항

- 팀 초대 리스트 조회

## 중점 사항

- teamInvitationService 에 UserService를 주입 받으면 TeamUserService와 순환 참조가 날 것 같아 임시적으로 UserRepository를 주입 받았습니다.

2021-12-15 19:01 UTC, samkimuel requested changes

2021-12-15 19:01 UTC, samkimuel commented on src/main/java/com/matchus/domains/team/controller/TeamInvitationController.java
> +			JwtAuthentication authentication
여기 줄 개행인건가용??

2021-12-15 19:01 UTC, samkimuel commented on src/main/java/com/matchus/domains/team/service/TeamInvitationService.java
>  	}
UserService를 주입받아도 순환참조 문제가 일어나지 않을 것 같은데 한번 테스트해보시는것도 좋을 것 같아요!

2021-12-15 19:07 UTC, sunH0 commented on src/main/java/com/matchus/domains/team/controller/TeamInvitationController.java
> +			JwtAuthentication authentication
줄 개행 없는 것으로 수정했어요~

2021-12-15 19:08 UTC, sunH0 commented on src/main/java/com/matchus/domains/team/service/TeamInvitationService.java
>  	}
문제 없네요 UserService로 수정하겠습니다!

2021-12-16 06:55 UTC, samkimuel approved these changes
끝까지 가봅시당!

2021-12-16 06:58 UTC, merged